// Generated by [preparation](prepare.mjs).
export const ROUND="pilot_literature_history_v0:pilot-v0.5:ff58e9109dcf1697815d206101ad1a839c368a365d573fea52ac03c321d493bd";
export const PLAN={
  "Q1e7d33f27419": {
    "owner": "A",
    "units": [
      "p0:n1",
      "p0:n2",
      "p0:n3"
    ]
  },
  "Q3542e9f4abe3": {
    "owner": "A",
    "units": [
      "p0:n1",
      "p0:n2",
      "p0:n3"
    ]
  },
  "Q231b21c4a116": {
    "owner": "B",
    "units": [
      "boundary"
    ]
  },
  "Qb7791769dbef": {
    "owner": "B",
    "units": [
      "p0:n1",
      "p0:n2",
      "p0:n3"
    ]
  },
  "Q63ae9bf08b31": {
    "owner": "B",
    "units": [
      "p0:n1",
      "p0:n2",
      "p0:n3"
    ]
  },
  "Q6895a41726b5": {
    "owner": "A",
    "units": [
      "boundary"
    ]
  },
  "Q6cbd045ef5f7": {
    "owner": "B",
    "units": [
      "p0:Ln1",
      "p0:Ln2",
      "p0:Rn1",
      "p0:Rn2",
      "p0:compare"
    ]
  },
  "Q9a4def3a6879": {
    "owner": "A",
    "units": [
      "p0:Ln1",
      "p0:Ln2",
      "p0:Rn1",
      "p0:Rn2",
      "p0:compare"
    ]
  },
  "Q1bd6712b75ee": {
    "owner": "A",
    "units": [
      "boundary"
    ]
  },
  "Q711fe20a672d": {
    "owner": "A",
    "units": [
      "p0:Ln1",
      "p0:Ln2",
      "p0:Rn1",
      "p0:Rn2",
      "p0:compare"
    ]
  },
  "Q39db32d2a2b5": {
    "owner": "B",
    "units": [
      "p0:Ln1",
      "p0:Ln2",
      "p0:Rn1",
      "p0:Rn2",
      "p0:compare"
    ]
  },
  "Qd89b12d24547": {
    "owner": "B",
    "units": [
      "boundary"
    ]
  },
  "Qdaabea0542e0": {
    "owner": "B",
    "units": [
      "p0:n1",
      "p0:n2",
      "p0:n3"
    ]
  },
  "Q7fedb395855d": {
    "owner": "B",
    "units": [
      "p0:alias",
      "p0:n1",
      "p0:n2",
      "p0:n3",
      "p1:alias",
      "p1:n1",
      "p1:n2",
      "p1:n3"
    ]
  },
  "Q52b58dc11743": {
    "owner": "A",
    "units": [
      "boundary"
    ]
  },
  "Qc56c963f4264": {
    "owner": "A",
    "units": [
      "p0:n1",
      "p0:n2",
      "p0:n3"
    ]
  },
  "Q77713ba09858": {
    "owner": "A",
    "units": [
      "p0:n1",
      "p0:n2",
      "p0:n3"
    ]
  },
  "Qb1b05c279e48": {
    "owner": "B",
    "units": [
      "p0:alias",
      "p0:n1",
      "p0:n2",
      "p0:n3",
      "p1:alias",
      "p1:n1",
      "p1:n2",
      "p1:n3"
    ]
  },
  "Qb278aaaddef5": {
    "owner": "A",
    "units": [
      "boundary"
    ]
  },
  "Qff9f45181cf9": {
    "owner": "B",
    "units": [
      "p0:n1",
      "p0:n2",
      "p0:n3"
    ]
  },
  "Qd43ce2eb5f22": {
    "owner": "B",
    "units": [
      "p0:n1",
      "p0:n2",
      "p0:n3"
    ]
  },
  "Qd90aa90ae9b6": {
    "owner": "A",
    "units": [
      "p0:n1",
      "p0:n2",
      "p0:n3",
      "p1:n1",
      "p1:n2",
      "p1:n3"
    ]
  },
  "Q4e6bf98987ca": {
    "owner": "B",
    "units": [
      "boundary"
    ]
  },
  "Q491db78b5f05": {
    "owner": "A",
    "units": [
      "p0:n1",
      "p0:n2",
      "p0:n3"
    ]
  },
  "Q5dea48d1ad16": {
    "owner": "A",
    "units": [
      "boundary"
    ]
  },
  "Qf0a0e6f8bf91": {
    "owner": "B",
    "units": [
      "p0:n1",
      "p0:n2",
      "p0:n3",
      "p1:n1",
      "p1:n2",
      "p1:n3"
    ]
  },
  "Qf0733a186ada": {
    "owner": "A",
    "units": [
      "p0:n1",
      "p0:n2",
      "p0:n3"
    ]
  },
  "Q427a5cd6fef1": {
    "owner": "B",
    "units": [
      "p0:n1",
      "p0:n2",
      "p0:n3",
      "p1:n1",
      "p1:n2",
      "p1:n3"
    ]
  },
  "Q3d6123a7019f": {
    "owner": "A",
    "units": [
      "boundary"
    ]
  },
  "Qff65feba67dd": {
    "owner": "B",
    "units": [
      "p0:n1",
      "p0:n2",
      "p0:n3"
    ]
  },
  "Q7f3c4bce2ed5": {
    "owner": "B",
    "units": [
      "boundary"
    ]
  },
  "Q511b569c3b0e": {
    "owner": "A",
    "units": [
      "p0:n1",
      "p0:n2",
      "p0:n3",
      "p1:n1",
      "p1:n2",
      "p1:n3"
    ]
  },
  "Q33672e55bfde": {
    "owner": "A",
    "units": [
      "p0:n1",
      "p0:n2",
      "p0:n3"
    ]
  },
  "Q377041dabb96": {
    "owner": "B",
    "units": [
      "p0:n1",
      "p0:n2",
      "p0:n3"
    ]
  },
  "Qeffd320f95f2": {
    "owner": "A",
    "units": [
      "boundary"
    ]
  },
  "Qa855de44003d": {
    "owner": "B",
    "units": [
      "p0:n1",
      "p0:n2",
      "p0:n3"
    ]
  },
  "Q7453a98ae6f8": {
    "owner": "B",
    "units": [
      "p0:n1",
      "p0:n2",
      "p0:n3"
    ]
  },
  "Q7a6707a85576": {
    "owner": "A",
    "units": [
      "boundary"
    ]
  },
  "Qdabbceeb15ad": {
    "owner": "A",
    "units": [
      "p0:scope",
      "p0:roster",
      "p0:author0",
      "p0:filter0",
      "p0:pages0",
      "p0:author1",
      "p0:filter1",
      "p0:pages1",
      "p0:author2",
      "p0:filter2",
      "p0:sum"
    ]
  },
  "Q38a9e1d39fd1": {
    "owner": "A",
    "units": [
      "p0:scope",
      "p0:roster",
      "p0:author0",
      "p0:filter0",
      "p0:pages0",
      "p0:author1",
      "p0:filter1",
      "p0:pages1",
      "p0:author2",
      "p0:filter2",
      "p0:sum"
    ]
  },
  "Q47af1d635e28": {
    "owner": "B",
    "units": [
      "boundary"
    ]
  },
  "Qa8ea0534afb0": {
    "owner": "A",
    "units": [
      "p0:scope",
      "p0:roster",
      "p0:author0",
      "p0:filter0",
      "p0:pages0",
      "p0:author1",
      "p0:filter1",
      "p0:pages1",
      "p0:author2",
      "p0:filter2",
      "p0:sum"
    ]
  },
  "Q92562e8e22a7": {
    "owner": "B",
    "units": [
      "p0:scope",
      "p0:roster",
      "p0:author0",
      "p0:filter0",
      "p0:pages0",
      "p0:author1",
      "p0:filter1",
      "p0:pages1",
      "p0:author2",
      "p0:filter2",
      "p0:sum"
    ]
  },
  "Qce58d35f9881": {
    "owner": "B",
    "units": [
      "boundary"
    ]
  },
  "Qc013df024eff": {
    "owner": "B",
    "units": [
      "p0:n1",
      "p0:n2",
      "p0:n3"
    ]
  },
  "Q87346a0d5da7": {
    "owner": "A",
    "units": [
      "p0:n1",
      "p0:n2",
      "p0:n3"
    ]
  },
  "Q05385011f2f3": {
    "owner": "A",
    "units": [
      "boundary"
    ]
  },
  "Qce4f9650ce25": {
    "owner": "A",
    "units": [
      "p0:n1",
      "p0:n2",
      "p0:n3"
    ]
  },
  "Qdd95a58d8636": {
    "owner": "B",
    "units": [
      "p0:n1",
      "p0:n2",
      "p0:n3"
    ]
  },
  "Q3a573d63b015": {
    "owner": "B",
    "units": [
      "p0:n1",
      "p0:n2",
      "p0:n3"
    ]
  },
  "Q9b35ed73273d": {
    "owner": "B",
    "units": [
      "p0:n1",
      "p0:n2",
      "p0:n3"
    ]
  },
  "Qa5138e7eda71": {
    "owner": "A",
    "units": [
      "p0:n1",
      "p0:n2",
      "p0:n3"
    ]
  },
  "Qe37a1b3051af": {
    "owner": "A",
    "units": [
      "boundary"
    ]
  },
  "Qd75ba6aeba3f": {
    "owner": "B",
    "units": [
      "p0:n1",
      "p0:n2",
      "p0:n3"
    ]
  },
  "Qe56935e35e3c": {
    "owner": "B",
    "units": [
      "p0:n1",
      "p0:n2",
      "p0:n3"
    ]
  },
  "Q7e1af4d674b8": {
    "owner": "A",
    "units": [
      "p0:n1",
      "p0:n2",
      "p0:n3"
    ]
  },
  "Qf67ddce79ece": {
    "owner": "B",
    "units": [
      "p0:n1",
      "p0:n2",
      "p0:n3"
    ]
  },
  "Q3ade916ae5a0": {
    "owner": "B",
    "units": [
      "p0:n1",
      "p0:n2",
      "p0:n3"
    ]
  },
  "Q51e80463a02b": {
    "owner": "A",
    "units": [
      "boundary"
    ]
  },
  "Q9d08a69fb13f": {
    "owner": "A",
    "units": [
      "p0:n1",
      "p0:n2",
      "p0:n3"
    ]
  },
  "Q3461f6e169d1": {
    "owner": "A",
    "units": [
      "p0:n1",
      "p0:n2",
      "p0:n3"
    ]
  },
  "Q9c506578a2ca": {
    "owner": "B",
    "units": [
      "p0:n1",
      "p0:n2",
      "p0:n3"
    ]
  },
  "Qc94a0ad18f44": {
    "owner": "A",
    "units": [
      "p0:n1",
      "p0:n2",
      "p0:n3"
    ]
  },
  "Qa5bb22039125": {
    "owner": "B",
    "units": [
      "p0:n1",
      "p0:n2",
      "p0:n3"
    ]
  },
  "Q906467871315": {
    "owner": "B",
    "units": [
      "boundary"
    ]
  },
  "Q963f0c98514a": {
    "owner": "A",
    "units": [
      "p0:n1",
      "p0:n2",
      "p0:n3"
    ]
  },
  "Qf22e27dcec0b": {
    "owner": "B",
    "units": [
      "p0:n1",
      "p0:n2",
      "p0:n3"
    ]
  },
  "Q0c2c24a370b9": {
    "owner": "A",
    "units": [
      "p0:n1",
      "p0:n2",
      "p0:n3"
    ]
  },
  "Q6bcf5862fa6a": {
    "owner": "B",
    "units": [
      "p0:n1",
      "p0:n2",
      "p0:n3"
    ]
  },
  "Qc25be0cfa138": {
    "owner": "B",
    "units": [
      "p0:n1",
      "p0:check"
    ]
  },
  "Q7cd4c9c86ce8": {
    "owner": "A",
    "units": [
      "boundary"
    ]
  },
  "Q01bed80ee24a": {
    "owner": "A",
    "units": [
      "p0:n1",
      "p0:assume",
      "p0:derive"
    ]
  },
  "Q8ec64c73941e": {
    "owner": "A",
    "units": [
      "p0:n1",
      "p0:n2",
      "p0:n3"
    ]
  },
  "Q54ecb7d32ab0": {
    "owner": "B",
    "units": [
      "p0:n1",
      "p0:check"
    ]
  },
  "Q017079d3395d": {
    "owner": "A",
    "units": [
      "boundary"
    ]
  },
  "Qd18640b9f9f0": {
    "owner": "B",
    "units": [
      "p0:n1",
      "p0:assume",
      "p0:derive"
    ]
  },
  "Qd14c7763a17f": {
    "owner": "A",
    "units": [
      "p0:n1",
      "p0:n2",
      "p0:n3",
      "p0:n4"
    ]
  },
  "Qbc91779de3a8": {
    "owner": "B",
    "units": [
      "p0:n1",
      "p0:n2",
      "p0:n3",
      "p0:n4"
    ]
  },
  "Q517fb4f817be": {
    "owner": "B",
    "units": [
      "boundary"
    ]
  },
  "Q37e9c2351e90": {
    "owner": "A",
    "units": [
      "p0:n1",
      "p0:n2",
      "p0:n3",
      "p0:n4"
    ]
  },
  "Q869f389e8996": {
    "owner": "A",
    "units": [
      "p0:n1",
      "p0:n2",
      "p0:n3",
      "p0:n4",
      "p1:n1",
      "p1:n2",
      "p1:n3",
      "p1:n4"
    ]
  },
  "Q70cc7faaa707": {
    "owner": "A",
    "units": [
      "p0:n1",
      "p0:n2",
      "p0:n3",
      "p0:n4"
    ]
  },
  "Qf732f736a8a6": {
    "owner": "B",
    "units": [
      "p0:n1",
      "p0:n2",
      "p0:n3",
      "p0:n4"
    ]
  },
  "Qcbaf77759104": {
    "owner": "A",
    "units": [
      "boundary"
    ]
  },
  "Q281b47b264d5": {
    "owner": "B",
    "units": [
      "p0:n1",
      "p0:n2",
      "p0:n3",
      "p0:n4"
    ]
  },
  "Q865f07e144d6": {
    "owner": "B",
    "units": [
      "p0:n1",
      "p0:n2",
      "p0:n3",
      "p0:n4",
      "p1:n1",
      "p1:n2",
      "p1:n3",
      "p1:n4"
    ]
  }
};
