// [Preparation workflow](README.md).
import {readFileSync,writeFileSync,copyFileSync} from 'node:fs';
import {assignment,units,datasetKey} from '../web/review-model.js';
const bundle=JSON.parse(readFileSync(new URL('../../workspace/pages/api/datasets/pilot_literature_history_v0/bundle.json',import.meta.url),'utf8'));
const owners=assignment(bundle.records),plan=Object.fromEntries(bundle.records.map(r=>[r.id,{owner:owners[r.id],units:units(r).map(u=>u.key)}]));
copyFileSync(new URL('../web/review-model.js',import.meta.url),new URL('./review-model.js',import.meta.url));
writeFileSync(new URL('./plan.js',import.meta.url),'// Generated by [preparation](prepare.mjs).\nexport const ROUND='+JSON.stringify(datasetKey(bundle))+';\nexport const PLAN='+JSON.stringify(plan,null,2)+';\n');
console.log('Prepared '+bundle.records.length+' assigned review tasks');
