'use strict';
const S=window.BRIDGEQA_STATE, $=id=>document.getElementById(id), J=x=>serializeJSON(x,2);
const cases=[...S.samples,...S.fixtures.samples], publicInputs=[...S.inputs,...S.fixtures.inputs], cachedPredictions=[...S.predictions,...S.fixtures.predictions];
const labels={gold_only:'仅原文',clean_control:'匹配对照',adversarial:'攻击'}, mechanisms={false_bridge:'错误桥接',redundant:'冗余',misleading_relation:'相似关系'};
let current,lastScore=null;
$('vocabulary-help').textContent=S.inputs[0].instruction;
function requireFinite(value){if(typeof value==='number'&&!Number.isFinite(value))throw new Error('JSON含非有限数值；原编辑文本保留，请修正后再提交。');if(value&&typeof value==='object')for(const item of Object.values(value))requireFinite(item);return value;}
function serializeJSON(value,space){return JSON.stringify(requireFinite(value),null,space);}
function parseEditor(text){return requireFinite(JSON.parse(text));}
function el(tag,text,cls){const n=document.createElement(tag);if(text!==undefined)n.textContent=text;if(cls)n.className=cls;return n;}
function option(value,text){const n=el('option',text);n.value=value;return n;}
function table(parent,heads,rows){const t=el('table'),tr=el('tr');heads.forEach(h=>tr.append(el('th',h)));const th=el('thead');th.append(tr);t.append(th);const b=el('tbody');rows.forEach(row=>{const r=el('tr');row.forEach(v=>r.append(el('td',String(v??'null'))));b.append(r);});t.append(b);parent.append(t);}
function metricCards(parent,values){parent.replaceChildren();values.forEach(([v,label])=>{const c=el('div',undefined,'card');c.append(el('strong',String(v)),el('span',label));parent.append(c);});}
function loadPrediction(p,label){$('status').value=p.status;$('answer').disabled=p.status!=='ok';$('answer').value=p.answer?.text||'';$('steps').value=J(p.submitted_steps||[]);$('support').value=J(p.support||[]);$('editor-status').textContent=label;$('score-result').replaceChildren();lastScore=null;}
function referencePrediction(){const steps=current.proofs[0].steps,support=[];for(const s of steps)for(const r of s.evidence)if(!support.some(x=>J(x)===J(r)))support.push(r);return {schema_version:'0.2',sample_id:current.sample_id,run_id:'user-demo-reference',status:'ok',answer:{text:current.answer.text},support,submitted_steps:steps};}
function submission(){return {schema_version:'0.2',sample_id:current.sample_id,run_id:'user-demo-edit',status:$('status').value,answer:$('status').value==='ok'?{text:$('answer').value}:null,submitted_steps:parseEditor($('steps').value),support:parseEditor($('support').value)};}
function seedChanged(){const records=cases.filter(s=>s.seed_id===$('seed').value);$('condition').replaceChildren(...records.map(s=>option(s.sample_id,`${labels[s.variant]}${s.attack?' / '+mechanisms[s.attack.primary_type]:s.pair_id?' / '+mechanisms[cases.find(x=>x.pair_id===s.pair_id&&x.attack).attack.primary_type]:''}`)));renderCase();}
function renderCase(){current=cases.find(s=>s.sample_id===$('condition').value);$('question').textContent=current.question;$('case-meta').textContent=`${current.hop_count} 跳 · ${current.source_cluster} · ${current.origin === "fictional_fixture" ? "虚构工具夹具，不计候选成绩" : "candidate"}`;$('documents').replaceChildren();const input=publicInputs.find(i=>i.sample_id===current.sample_id);input.documents.forEach(d=>{const box=el('div',undefined,'document');box.append(el('h4',`${d.doc_id} · ${d.title}`));d.sentences.forEach(s=>{const row=el('div',undefined,'sentence'+(s.text.includes('合成练习')?' synthetic':''));row.append(el('span',`${d.doc_id}:${s.sent_id}`,'ref'),el('span',s.text));box.append(row);});$('documents').append(box);});$('input-preview').textContent=J(input);$('reference').textContent=J({answer:current.answer,entity_aliases:current.entity_aliases,proofs:current.proofs});$('pair-diff').replaceChildren();if(!current.pair_id){$('pair-diff').append(el('p','gold_only 没有成对干扰槽。请选择匹配对照或攻击条件。'));}else{const c=cases.find(s=>s.pair_id===current.pair_id&&s.variant==='clean_control'),a=cases.find(s=>s.pair_id===current.pair_id&&s.variant==='adversarial');for(const ref of a.attack.changed_sentences){const text=s=>s.documents.find(d=>d.doc_id===ref.doc_id).sentences.find(x=>x.sent_id===ref.sent_id).text;const x=el('div',undefined,'diff');x.append(el('b',`${ref.doc_id}:${ref.sent_id} · ${mechanisms[a.attack.primary_type]}`),el('p','对照：'+text(c)),el('p','攻击：'+text(a)));$('pair-diff').append(x);}const cLen=JSON.stringify(c.documents.map(d=>d.sentences.map(s=>s.text))).length,aLen=JSON.stringify(a.documents.map(d=>d.sentences.map(s=>s.text))).length;$('pair-diff').append(el('p',`当前槽外正文完全相同。正文字符长度差 0%；token 未测（null）。合成角色明确不属于原著，攻击效力仍待人工及模型检验。`));}
loadPrediction(cachedPredictions.find(p=>p.sample_id===current.sample_id),'已载入本轮真实规则运行缓存；可修改或重新运行。');}
async function api(path,data){requireFinite(data);if(location.protocol==='file:')throw new Error('静态缓存是设计回退；实时运行和评分请启动本地HTTP服务。');const r=await fetch(path,{method:'POST',headers:{'Content-Type':'application/json'},body:serializeJSON(data)});const x=await r.json();if(!r.ok)throw new Error(x.error||r.status);return x;}
async function action(fn){try{$('editor-status').className='';await fn();}catch(e){$('score-result').replaceChildren();lastScore=null;$('editor-status').textContent=e.message;$('editor-status').className='error';}}
document.querySelectorAll('nav button').forEach(b=>b.onclick=()=>{document.querySelectorAll('.page').forEach(p=>p.hidden=p.id!==b.dataset.page);document.querySelectorAll('nav button').forEach(n=>n.classList.toggle('selected',n===b));});
$('seed').replaceChildren(...[...new Set(cases.map(s=>s.seed_id))].map(id=>{const s=cases.find(s=>s.seed_id===id);return option(id,`${id} · ${s.hop_count}跳 · ${s.proofs[0].steps[0].head}`);}));$('status').onchange=()=>{$('answer').disabled=$('status').value!=='ok';};$('seed').onchange=seedChanged;$('condition').onchange=renderCase;$('toggle-input').onclick=()=>{$('input-preview').hidden=!$('input-preview').hidden;};
$('load-reference').onclick=()=>loadPrediction(referencePrediction(),'已载入待审参考，仅作评分演示，不是模型预测。');
$('break-path').onclick=()=>action(async()=>{const steps=parseEditor($('steps').value);if(!steps.length)throw new Error('先载入证明');steps[0].relation='故意错误关系';$('steps').value=J(steps);$('editor-status').textContent='答案未变，首跳关系已故意改坏；请提交评分。';});
$('run-baseline').onclick=()=>action(async()=>loadPrediction(await api('/api/baseline',{sample_id:current.sample_id}),'已实际重新运行正文规则，未读取参考标签。'));
$('score').onclick=()=>action(async()=>{const p=submission();lastScore=await api('/api/score',{sample_id:current.sample_id,prediction:p});metricCards($('score-result'),[['EM '+lastScore.answer_em,'独立答案'],['F1 '+lastScore.support_f1,'全局支持'],['SR '+lastScore.strict_sr,'严格成功'],['CFS '+lastScore.path_cfs,'正确前缀 / 100']]);$('score-result').append(el('pre',J(lastScore)));$('editor-status').textContent='本地评分已完成；候选参考不代表人工认证。';});
$('export').onclick=()=>action(async()=>{const result=await api('/api/export',{sample_id:current.sample_id,prediction:submission()});$('editor-status').textContent='已重新评分并保存到本次运行目录：'+result.saved;const link=el('a','查看已保存的提交 JSON');link.href=result.url;link.target='_blank';$('score-result').replaceChildren(link,el('pre',J(result.export)));});
const c=S.score.partitions.candidate;metricCards($('result-cards'),[['22 / 6','候选记录 / 种子'],[c.metrics.answer_em,'候选 Answer EM'],[c.metrics.strict_sr,'候选 Strict SR'],['0 / null','正式题 / 正式成绩']]);
table($('result-tables'),['条件','种子宏 EM','Strict SR','Path-CFS'],Object.entries(c.by_variant_seed_macro).map(([k,v])=>[labels[k],v.answer_em,v.strict_sr,v.path_cfs]));table($('result-tables'),['机制','配对 / 种子','SR Drop /百分点','ASR 分子 / 分母','种子加权ASR'],Object.entries(c.paired_by_mechanism).map(([k,v])=>[mechanisms[k],`${v.pairs} / ${v.seeds}`,v.metrics.strict_sr.drop_percentage_points,`${v.metrics.strict_sr.asr_numerator} / ${v.metrics.strict_sr.asr_denominator}`,v.metrics.strict_sr.seed_weighted_asr]));$('result-tables').append(el('p','当前表格显示本会话实际规则缓存成绩。自然问句去掉显式中间姓名提示，但真名题仍可有知识捷径；规则结果不能证明未知模型能力、必要内部多跳或攻击有效性。'));
table($('oracle-table'),['独立条件','节点成功 / 总数','父记录 / 种子','seed macro Oracle-CS'],Object.entries(S.oracle_score.by_variant).map(([k,v])=>[labels[k],`${v.node_successes} / ${v.nodes}`,`${v.samples} / ${v.seeds}`,v.seed_macro_oracle_cs]));$('manifest').textContent=J(S.manifest);
$('download-results').onclick=()=>{const result={scope:'separate_actual_rule_tracks_not_llm',candidate:{score:S.score,oracle_score:S.oracle_score},controlled:{score:S.controlled.score,manifest:S.controlled.manifest,audit:S.controlled.audit},manifest:S.manifest,score:S.score,oracle_score:S.oracle_score};const parent=$('result-export');parent.replaceChildren();if(location.protocol==='file:'){parent.append(el('p','这是静态缓存预览；请启动本地服务后查看并另存 /results.json。'));}else{const a=el('a','查看并另存真实结果 JSON');a.href='/results.json';a.target='_blank';parent.append(a);}parent.append(el('pre',J(result)));};
const registry=S.sources.sources||S.sources;const sources=Array.isArray(registry)?registry:Object.values(registry);for(const source of sources){if(!source||!source.url)continue;const row=el('div',undefined,'source'),a=el('a',source.citation||source.source_id||source.url);a.href=source.url;a.target='_blank';a.rel='noopener';row.append(a,el('p',`${source.version||''} · ${source.license||''}`));$('source-list').append(row);}$('spans').textContent=J(S.spans);$('original-spans').textContent=J(S.original_spans);$('derivation-ledger').textContent=J(S.derivation_ledger);$('sources-json').textContent=J(S.sources);$('ledger').textContent=J(S.review_ledger);seedChanged();
// Controlled reference is evaluator-side viewing data. Only sample_id selects
// the frozen safe input at /api/controlled/baseline; no reference is sent.
const C=S.controlled, controlledLabels={full:'全部资料', 'order-shuffle':'顺序打乱', 'internal-reroute':'内部桥接替换', 'delete-hop':'逐跳缺证', 'no-context':'无事实资料'};
let controlledCurrent;
function renderDocuments(parent,input){parent.replaceChildren();for(const d of input.documents){const box=el('div',undefined,'document');box.append(el('h4',`${d.doc_id} · ${d.title}`));for(const sentence of d.sentences){const row=el('div',undefined,'sentence');row.append(el('span',`${d.doc_id}:${sentence.sent_id}`,'ref'),el('span',sentence.text));box.append(row);}parent.append(box);}}
function controlledLoad(p,label){$('controlled-status').value=p.status;$('controlled-answer').value=p.answer?.text||'';$('controlled-answer').disabled=p.status!=='ok';$('controlled-steps').value=J(p.submitted_steps||[]);$('controlled-support').value=J(p.support||[]);$('controlled-editor-status').textContent=label;$('controlled-score-result').replaceChildren();}
function controlledSubmission(){const status=$('controlled-status').value;return {schema_version:'0.2',sample_id:controlledCurrent.sample_id,run_id:'user-controlled-edit',status,answer:status==='ok'?{text:$('controlled-answer').value}:null,submitted_steps:parseEditor($('controlled-steps').value),support:parseEditor($('controlled-support').value)};}
async function controlledAction(fn){try{$('controlled-editor-status').className='';await fn();}catch(error){$('controlled-score-result').replaceChildren();$('controlled-editor-status').textContent=error.message;$('controlled-editor-status').className='error';}}
function controlledRootChanged(){const cases=C.reference.cases.filter(c=>c.root_id===$('controlled-root').value);$('controlled-condition').replaceChildren(...cases.map(c=>option(c.sample_id,controlledLabels[c.condition]+(c.intervention_hop?` · 第${c.intervention_hop}跳`:''))));controlledRender();}
function controlledRender(){controlledCurrent=C.reference.cases.find(c=>c.sample_id===$('controlled-condition').value);const c=controlledCurrent,input=C.inputs.find(i=>i.sample_id===c.sample_id),world=C.reference.worlds.find(w=>w.root_id===c.root_id),full=C.reference.cases.find(x=>x.root_id===c.root_id&&x.condition==='full'),fullInput=C.inputs.find(i=>i.sample_id===full.sample_id);$('controlled-question').textContent=input.question;$('controlled-meta').textContent=`${c.hop_count} 跳拓扑 · ${c.source_cluster} · ${c.expected_answerable?'参考可答':'参考资料不足'}`;$('controlled-candidates').textContent=`匹配比较的两个候选终点：${world.a_nodes.at(-1)} / ${world.b_nodes.at(-1)}。此处是评测查看信息，不追加到模型输入；候选出现本身不提供关系证据。`;$('controlled-input').textContent=J(input);renderDocuments($('controlled-documents'),input);$('controlled-reference').textContent=J(c);const parent=$('controlled-comparison');parent.replaceChildren();const p=C.predictions.find(p=>p.sample_id===c.sample_id),fp=C.predictions.find(p=>p.sample_id===full.sample_id);parent.append(el('p',`问题保持相同：${input.question===fullInput.question}。当前规则：${p.status} / ${p.answer?.text??'null'}；full规则：${fp.status} / ${fp.answer?.text??'null'}。`));if(c.condition==='order-shuffle')parent.append(el('p','同一事实集合改变顺序；材料编号同步重标，引用随之变化。'));else if(c.condition==='no-context')parent.append(el('p','不提供事实材料；固定问题保留，名册也不作为证据。'));else for(const slot of c.changed_slots){const find=(which,publicInput)=>{const ref=which.presentation.find(x=>x.slot_id===slot);return publicInput.documents.find(d=>d.doc_id===ref.doc_id).sentences.find(s=>s.sent_id===ref.sent_id).text;};const row=el('div',undefined,'diff');row.append(el('b',`登记变化槽 ${slot}（私有审计）`),el('p','full：'+find(full,fullInput)),el('p','当前：'+find(c,input)));parent.append(row);}controlledLoad(p,'已载入本会话实际独立规则缓存；可编辑或重新运行。');}
$('controlled-root').replaceChildren(...C.reference.worlds.map(w=>option(w.root_id,`${w.root_id} · ${w.hop_count}跳 · ${w.source_cluster}`)));
$('controlled-root').onchange=controlledRootChanged;$('controlled-condition').onchange=controlledRender;$('controlled-toggle-input').onclick=()=>{$('controlled-input').hidden=!$('controlled-input').hidden;};$('controlled-status').onchange=()=>{$('controlled-answer').disabled=$('controlled-status').value!=='ok';};
$('controlled-run').onclick=()=>controlledAction(async()=>controlledLoad(await api('/api/controlled/baseline',{sample_id:controlledCurrent.sample_id}),'已实际重新运行，只传该case安全输入。'));
$('controlled-score').onclick=()=>controlledAction(async()=>{const result=await api('/api/controlled/score',{sample_id:controlledCurrent.sample_id,prediction:controlledSubmission()});metricCards($('controlled-score-result'),[['合同 '+result.contract_success,'可答取SR / 不足取合法拒答'],['EM '+(result.answer_em??'null'),'答案'],['SR '+(result.strict_sr??'null'),'完整证明'],['拒答 '+(result.correct_refusal??'null'),'合同合法性']]);$('controlled-score-result').append(el('pre',J(result)));$('controlled-editor-status').textContent='独立受控评分完成；合法拒答不是语义或内部推理认证。';});
$('controlled-export').onclick=()=>controlledAction(async()=>{const result=await api('/api/controlled/export',{sample_id:controlledCurrent.sample_id,prediction:controlledSubmission()});const link=el('a','查看已保存的独立受控提交 JSON');link.href=result.url;link.target='_blank';$('controlled-score-result').replaceChildren(link,el('pre',J(result.export)));$('controlled-editor-status').textContent='已按同会话参考重新评分并保存：'+result.saved;});
metricCards($('controlled-cards'),[['46 / 6 / 3','条件 / 家族 / 来源拓扑簇'],['23 / 23','可答 / 资料不足'],[C.score.contract_success.root_macro,'合同成功：五类等权后root宏平均'],[`${C.score.bridge_sensitivity.successes} / ${C.score.bridge_sensitivity.pairs}`,'桥敏感性匹配成功 / 全部桥对']]);
table($('controlled-tables'),['独立条件','成功 / 分母','root宏合同','root宏SR','root宏合法拒答'],Object.entries(C.score.by_condition).map(([k,v])=>[controlledLabels[k],`${v.successes} / ${v.cases}`,v.root_macro.contract_success,v.root_macro.strict_sr,v.root_macro.correct_refusal]));$('controlled-tables').append(el('p','先在每家族内平均该条件的逐hop干预，再对6家族宏平均。46条是相关条件；可答EM/F1/SR/CFS、不足合法拒答与原始微均值分别保留。模型未运行（null）。'));$('controlled-score-json').textContent=J(C.score);$('controlled-manifest').textContent=J({manifest:C.manifest,audit:C.audit});controlledRootChanged();
